CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	name TEXT NOT NULL,
	password TEXT NOT NULL,
	joined_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS cats (
	id SERIAL PRIMARY KEY,
	name TEXT NOT NULL,
	description TEXT NOT NULL,
	location TEXT NOT NULL,
	added_at TIMESTAMPTZ DEFAULT now(),
	vet_id INT
);

CREATE TABLE IF NOT EXISTS user_cat (
	id SERIAL PRIMARY KEY,
	user_id INT NOT NULL,
	cat_id INT NOT NULL
);

CREATE TABLE IF NOT EXISTS followers (
	id SERIAL PRIMARY KEY,
	user_id INT NOT NULL,
	follower_id INT NOT NULL
);